### ISSUE TITLE
Variables not being applied

### ISSUE THREAD

**Issue by Schmoopy** [maztch/laravel-elixir-materialize#1]
Hey, thanks for making this loader, there does seem to be an issue with variables being set however.

Here's my setup:

resources/assets/_variables-materialize.scss

    $primary-color: color('yellow', 'lighten-1');
    $secondary-color: color('yellow', 'lighten-1');

But when I run gulp nothing changes and the colours stay the default.

If I go directly into materialize-css/sass/components/_variables.scss and set these variables there then it works.

Is this a bug or am I doing something wrong? (v1.0.2)

**Comment by maztch** [comment]
I changed the way colors are imported, it's a problem about the way scss files are imported.

I fixed in new version 1.0.3, pls, just update the package.

**Comment by Schmoopy** [comment]
Great that's fixed it, thanks :)
